### ISSUE TITLE
新增自定义颜色导出无效

### ISSUE THREAD

**Issue by yanc233** [arco-design/color#4]
![03a5e126-ff8b-4ccc-b676-faad37cc083f](https://user-images.githubusercontent.com/87287695/204184450-31ebbe29-21d1-4508-9356-7b7ca456ffb8.jpeg)
添加了自定义的颜色之后,导出的文件中,并没有添加的颜色,只存在原来的默认颜色列表
![09f4a552-fe04-4690-a118-30b7864b2599](https://user-images.githubusercontent.com/87287695/204184484-3990ac11-b8ed-475e-a74e-8868c957ce4f.jpeg)
导出的less文件中,并没有temp

**Comment by PengJiyuan** [comment]
已上线
